/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingSystem;

/**
 *
 * @author Administrator
 */
public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbWithdrawMenu = new javax.swing.JButton();
        jbLogout = new javax.swing.JButton();
        jbDepositMenu = new javax.swing.JButton();
        jbBalanceMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbWithdrawMenu.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jbWithdrawMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/money-withdrawal (1).png"))); // NOI18N
        jbWithdrawMenu.setText("Withdraw");
        jbWithdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbWithdrawMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jbWithdrawMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 60));

        jbLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbLogout.setForeground(new java.awt.Color(255, 0, 0));
        jbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logout.png"))); // NOI18N
        jbLogout.setText("Log Out");
        jbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 50));

        jbDepositMenu.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jbDepositMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/deposit.png"))); // NOI18N
        jbDepositMenu.setText("Deposit");
        jbDepositMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDepositMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jbDepositMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 60));

        jbBalanceMenu.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jbBalanceMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/wallet.png"))); // NOI18N
        jbBalanceMenu.setText("Balance");
        jbBalanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBalanceMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jbBalanceMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/passbook.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 260, 260));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 480, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbWithdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbWithdrawMenuActionPerformed
        this.setVisible(false);
        new withdrawframe().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbWithdrawMenuActionPerformed

    private void jbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogoutActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbLogoutActionPerformed

    private void jbDepositMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDepositMenuActionPerformed
        this.setVisible(false);
        new deposit_frame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbDepositMenuActionPerformed

    private void jbBalanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBalanceMenuActionPerformed
        this.setVisible(false);
        new balance().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbBalanceMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mainpage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBalanceMenu;
    private javax.swing.JButton jbDepositMenu;
    private javax.swing.JButton jbLogout;
    private javax.swing.JButton jbWithdrawMenu;
    // End of variables declaration//GEN-END:variables
}
